window.env = {
  "rvm_use_flag": "",
  "rvm_bin_path": "/Users/jshrivastava/.rvm/bin",
  "TERM_PROGRAM": "Apple_Terminal",
  "NODE": "/usr/local/Cellar/node/15.4.0/bin/node",
  "INIT_CWD": "/Users/jshrivastava/code/jayshrivastava.github.io",
  "rvm_quiet_flag": "",
  "GEM_HOME": "/Users/jshrivastava/.rvm/gems/ruby-2.5.1",
  "npm_package_homepage": "http://jayshrivastava.github.io/",
  "npm_config_version_git_tag": "true",
  "rvm_gemstone_url": "",
  "SHELL": "/bin/zsh",
  "TERM": "xterm-256color",
  "npm_package_dependencies_react_dotenv": "^0.1.2",
  "rvm_docs_type": "",
  "IRBRC": "/Users/jshrivastava/.rvm/rubies/ruby-2.5.1/.irbrc",
  "TMPDIR": "/var/folders/rl/cxwjpxdx4l3btdjvjgg7dpr80000gn/T/",
  "npm_package_devDependencies_tslint": "^6.1.3",
  "npm_package_devDependencies_interweave": "^12.6.0",
  "npm_config_metrics_registry": "https://registry.yarnpkg.com/",
  "GOBIN": "/Users/jshrivastava/go/bin",
  "npm_package_scripts_lint": "tslint 'src/**/*.ts?(x)' --fix",
  "npm_package_dependencies_react_bootstrap": "^1.4.0",
  "npm_config_init_license": "MIT",
  "TERM_PROGRAM_VERSION": "433",
  "npm_package_dependencies_react_theme_toggle_button": "^1.1.0",
  "rvm_hook": "",
  "MY_RUBY_HOME": "/Users/jshrivastava/.rvm/rubies/ruby-2.5.1",
  "TERM_SESSION_ID": "641BB426-0973-4695-9B5D-D70636482AEF",
  "COLOR": "1",
  "npm_package_private": "true",
  "npm_config_registry": "https://registry.yarnpkg.com",
  "npm_package_dependencies_react_dom": "^17.0.1",
  "npm_package_readmeFilename": "README.md",
  "USER": "jshrivastava",
  "npm_package_description": "### Requirements",
  "npm_package_dependencies_web_vitals": "^0.2.4",
  "npm_config_python": "/usr/bin/python",
  "rvm_gemstone_package_file": "",
  "npm_package_scripts_deploy": "gh-pages -d build",
  "npm_package_dependencies__testing_library_user_event": "^12.1.10",
  "npm_package_browserslist_development_1": "last 1 firefox version",
  "npm_config_globalconfig": "/usr/local/etc/npmrc",
  "rvm_path": "/Users/jshrivastava/.rvm",
  "npm_package_browserslist_development_0": "last 1 chrome version",
  "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.Jq766VKDmK/Listeners",
  "__CF_USER_TEXT_ENCODING": "0x1F5:0x0:0x52",
  "npm_package_browserslist_development_2": "last 1 safari version",
  "rvm_proxy": "",
  "npm_execpath": "/usr/local/lib/node_modules/npm/bin/npm-cli.js",
  "npm_package_scripts_predeploy": "npm run build",
  "rvm_ruby_file": "",
  "rvm_silent_flag": "",
  "rvm_prefix": "/Users/jshrivastava",
  "rvm_ruby_make": "",
  "PATH": "/Users/jshrivastava/code/jayshrivastava.github.io/node_modules/.bin:/Users/jshrivastava/code/node_modules/.bin:/Users/jshrivastava/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/var/folders/rl/cxwjpxdx4l3btdjvjgg7dpr80000gn/T/yarn--1610213889861-0.635890616121674:/Users/jshrivastava/code/jayshrivastava.github.io/node_modules/.bin:/Users/jshrivastava/.config/yarn/link/node_modules/.bin:/usr/local/Cellar/node/15.4.0/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/Cellar/node/15.4.0/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/Cellar/node/15.4.0/bin/node_modules/npm/bin/node-gyp-bin:/Users/jshrivastava/.rvm/gems/ruby-2.5.1/bin:/Users/jshrivastava/.rvm/gems/ruby-2.5.1@global/bin:/Users/jshrivastava/.rvm/rubies/ruby-2.5.1/bin:/Users/jshrivastava/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin::/Users/jshrivastava/go:/Users/jshrivastava/go/bin:/Users/jshrivastava/.rvm/bin",
  "npm_config_argv": "{\"remain\":[],\"cooked\":[\"run\",\"predeploy\"],\"original\":[\"deploy\"]}",
  "npm_config_init.module": "/Users/jshrivastava/.npm-init.js",
  "_": "/Users/jshrivastava/code/jayshrivastava.github.io/node_modules/.bin/react-dotenv",
  "npm_package_json": "/Users/jshrivastava/code/jayshrivastava.github.io/package.json",
  "npm_package_browserslist_production_1": "not dead",
  "npm_package_dependencies_typescript": "^4.1.2",
  "npm_package_dependencies__types_jest": "^26.0.15",
  "npm_config_init_module": "/Users/jshrivastava/.npm-init.js",
  "npm_config_userconfig": "/Users/jshrivastava/.npmrc",
  "PWD": "/Users/jshrivastava/code/jayshrivastava.github.io",
  "npm_package_browserslist_production_0": ">0.2%",
  "npm_package_dependencies_bootstrap": "^4.5.3",
  "npm_command": "run-script",
  "npm_lifecycle_event": "build",
  "npm_package_devDependencies__types_react_router_dom": "^5.1.6",
  "npm_package_browserslist_production_2": "not op_mini all",
  "EDITOR": "vi",
  "rvm_sdk": "",
  "LANG": "en_CA.UTF-8",
  "npm_package_name": "jayshrivastava.github.io",
  "npm_package_scripts_build": "react-dotenv && react-scripts build",
  "npm_package_scripts_start": "react-dotenv && react-scripts start",
  "npm_config_version_commit_hooks": "true",
  "XPC_FLAGS": "0x0",
  "npm_package_dependencies_react_router_dom": "^5.2.0",
  "npm_config_bin_links": "true",
  "npm_config_node_gyp": "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js",
  "XPC_SERVICE_NAME": "0",
  "npm_package_version": "0.1.0",
  "rvm_version": "1.29.9 (latest)",
  "rvm_script_name": "",
  "rvm_pretty_print_flag": "",
  "SHLVL": "3",
  "HOME": "/Users/jshrivastava",
  "rvm_ruby_mode": "",
  "npm_package_scripts_test": "react-dotenv && react-scripts test",
  "npm_config_save_prefix": "^",
  "npm_config_strict_ssl": "true",
  "npm_package_dependencies__testing_library_jest_dom": "^5.11.4",
  "npm_config_version_git_message": "v%s",
  "NPM_CONFIG_PYTHON": "/usr/bin/python",
  "npm_package_dependencies__types_node": "^12.0.0",
  "LOGNAME": "jshrivastava",
  "YARN_WRAP_OUTPUT": "false",
  "npm_package_dependencies_react_scripts": "4.0.1",
  "npm_config_cache": "/Users/jshrivastava/.npm",
  "PREFIX": "/usr/local",
  "rvm_alias_expanded": "",
  "npm_lifecycle_script": "react-dotenv && react-scripts build",
  "npm_package_devDependencies_gh_pages": "^3.1.0",
  "GEM_PATH": "/Users/jshrivastava/.rvm/gems/ruby-2.5.1:/Users/jshrivastava/.rvm/gems/ruby-2.5.1@global",
  "npm_package_eslintConfig_extends_1": "react-app/jest",
  "npm_package_dependencies_react": "^17.0.1",
  "GOPATH": "/Users/jshrivastava/go",
  "npm_package_eslintConfig_extends_0": "react-app",
  "npm_package_dependencies__types_react": "^16.9.53",
  "rvm_nightly_flag": "",
  "npm_package_dependencies__testing_library_react": "^11.1.0",
  "npm_config_version_git_sign": "",
  "npm_config_ignore_scripts": "",
  "npm_config_user_agent": "yarn/1.22.10 npm/? node/v15.4.0 darwin x64",
  "rvm_ruby_make_install": "",
  "rvm_niceness": "",
  "DISPLAY": "/private/tmp/com.apple.launchd.n07ry68YgR/org.macosforge.xquartz:0",
  "rvm_ruby_bits": "",
  "rvm_bin_flag": "",
  "npm_config_init_version": "1.0.0",
  "npm_config_ignore_optional": "",
  "rvm_only_path_flag": "",
  "RUBY_VERSION": "ruby-2.5.1",
  "npm_package_devDependencies_node_sass": "^4.14.1",
  "npm_package_scripts_eject": "react-scripts eject",
  "npm_package_dependencies__types_react_dom": "^16.9.8",
  "npm_node_execpath": "/usr/local/Cellar/node/15.4.0/bin/node",
  "npm_config_version_tag_prefix": "v",
  "npm_config_prefix": "/usr/local"
};