window.env = {
  "MANPATH": "/opt/local/share/man:",
  "TERM_PROGRAM": "WarpTerminal",
  "NODE": "/opt/homebrew/Cellar/node/23.9.0/bin/node",
  "INIT_CWD": "/Users/jayants/code/jayshrivastava.github.io",
  "NVM_CD_FLAGS": "-q",
  "npm_package_homepage": "http://jayshrivastava.github.io/",
  "npm_config_version_git_tag": "true",
  "SHELL": "/bin/zsh",
  "TERM": "xterm-256color",
  "WARP_HONOR_PS1": "0",
  "npm_package_dependencies_react_dotenv": "^0.1.2",
  "TMPDIR": "/var/folders/rh/b_sjx5297d1_91n_cfqcgw400000gn/T/",
  "HOMEBREW_REPOSITORY": "/opt/homebrew",
  "npm_package_devDependencies_tslint": "^6.1.3",
  "npm_package_devDependencies_interweave": "^13.1.0",
  "npm_package_scripts_lint": "tslint 'src/**/*.ts?(x)' --fix",
  "npm_package_dependencies_react_bootstrap": "^2.10.2",
  "npm_config_init_license": "MIT",
  "npm_config_global_prefix": "/Users/jayants/.npm-global",
  "TERM_PROGRAM_VERSION": "v0.2025.03.12.08.02.stable_03",
  "npm_package_dependencies_react_theme_toggle_button": "^1.1.0",
  "COLOR": "1",
  "npm_package_private": "true",
  "npm_config_registry": "https://registry.yarnpkg.com",
  "npm_config_noproxy": "",
  "ZSH": "/Users/jayants/.oh-my-zsh",
  "npm_package_dependencies_react_dom": "^18.2.0",
  "npm_config_local_prefix": "/Users/jayants/code/jayshrivastava.github.io",
  "npm_package_readmeFilename": "README.md",
  "USER": "jayants",
  "NVM_DIR": "/Users/jayants/.nvm",
  "npm_package_description": "### Requirements",
  "npm_package_dependencies_web_vitals": "^3.5.2",
  "LS_COLORS": "di=1;36:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43",
  "COMMAND_MODE": "unix2003",
  "npm_package_scripts_deploy": "gh-pages -d build",
  "npm_package_dependencies__testing_library_user_event": "^14.5.2",
  "npm_package_browserslist_development_1": "last 1 firefox version",
  "npm_config_globalconfig": "/Users/jayants/.npm-global/etc/npmrc",
  "npm_package_browserslist_development_0": "last 1 chrome version",
  "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.p8SFzSYnst/Listeners",
  "WARP_IS_LOCAL_SHELL_SESSION": "1",
  "__CF_USER_TEXT_ENCODING": "0x1F5:0x0:0x0",
  "npm_package_browserslist_development_2": "last 1 safari version",
  "npm_execpath": "/Users/jayants/.npm-global/lib/node_modules/npm/bin/npm-cli.js",
  "npm_package_scripts_predeploy": "npm run build",
  "WARP_USE_SSH_WRAPPER": "0",
  "PAGER": "less",
  "LSCOLORS": "Gxfxcxdxbxegedabagacad",
  "PATH": "/Users/jayants/code/jayshrivastava.github.io/node_modules/.bin:/Users/jayants/code/node_modules/.bin:/Users/jayants/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/Users/jayants/.npm-global/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/var/folders/rh/b_sjx5297d1_91n_cfqcgw400000gn/T/yarn--1743556655117-0.5309839403245513:/Users/jayants/code/jayshrivastava.github.io/node_modules/.bin:/Users/jayants/.config/yarn/link/node_modules/.bin:/opt/homebrew/Cellar/node/23.9.0/libexec/lib/node_modules/npm/bin/node-gyp-bin:/opt/homebrew/Cellar/node/23.9.0/lib/node_modules/npm/bin/node-gyp-bin:/opt/homebrew/Cellar/node/23.9.0/bin/node_modules/npm/bin/node-gyp-bin:/Users/jayants/.npm-global/bin:/Users/jayants/.local/bin:/opt/homebrew/opt/make/libexec/gnubin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/share/dotnet:~/.dotnet/tools:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/jayants/.local/bin:/Users/jayants/.cargo/bin:/Users/jayants/go/src/github.com/cockroachlabs/registration:/Users/jayants/go/bin:/Users/jayants/go/src/github.com/cockroachdb/cockroach/bin:/Users/jayants/projects/devtools/bin/:/Users/jayant.shrivastava/dd/experimental/teams/metrics-query:/opt/homebrew/bin/:/Users/jayants/.npm-global/bin:/Users/jayants/.npm-global",
  "npm_config_argv": "{\"remain\":[],\"cooked\":[\"run\",\"predeploy\"],\"original\":[\"deploy\"]}",
  "_": "/Users/jayants/code/jayshrivastava.github.io/node_modules/.bin/react-dotenv",
  "npm_package_json": "/Users/jayants/code/jayshrivastava.github.io/package.json",
  "__CFBundleIdentifier": "dev.warp.Warp-Stable",
  "npm_package_browserslist_production_1": "not dead",
  "npm_package_dependencies_typescript": "^5.4.3",
  "npm_package_dependencies__types_jest": "^29.5.12",
  "npm_config_init_module": "/Users/jayants/.npm-init.js",
  "npm_config_userconfig": "/Users/jayants/.npmrc",
  "PWD": "/Users/jayants/code/jayshrivastava.github.io",
  "npm_package_browserslist_production_0": ">0.2%",
  "npm_package_dependencies_bootstrap": "^5.3.3",
  "npm_command": "run-script",
  "npm_lifecycle_event": "build",
  "npm_package_devDependencies__types_react_router_dom": "^5.3.3",
  "npm_package_browserslist_production_2": "not op_mini all",
  "EDITOR": "vi",
  "LANG": "en_US.UTF-8",
  "npm_package_name": "jayshrivastava.github.io",
  "npm_package_scripts_build": "react-dotenv && react-scripts build",
  "npm_package_scripts_start": "react-dotenv && react-scripts start",
  "npm_config_version_commit_hooks": "true",
  "XPC_FLAGS": "0x0",
  "npm_package_dependencies_react_router_dom": "^6.22.3",
  "npm_config_npm_version": "10.9.2",
  "npm_config_bin_links": "true",
  "npm_config_node_gyp": "/Users/jayants/.npm-global/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js",
  "XPC_SERVICE_NAME": "0",
  "npm_package_version": "0.1.0",
  "HOME": "/Users/jayants",
  "SHLVL": "3",
  "GOROOT": "/usr/local/go",
  "npm_package_scripts_test": "react-dotenv && react-scripts test",
  "npm_config_save_prefix": "^",
  "npm_config_strict_ssl": "true",
  "HOMEBREW_PREFIX": "/opt/homebrew",
  "npm_package_dependencies__testing_library_jest_dom": "^6.4.2",
  "npm_config_version_git_message": "v%s",
  "npm_package_dependencies__types_node": "^20.11.30",
  "LOGNAME": "jayants",
  "LESS": "-R",
  "YARN_WRAP_OUTPUT": "false",
  "npm_package_dependencies_react_scripts": "^5.0.1",
  "npm_config_cache": "/Users/jayants/.npm",
  "npm_lifecycle_script": "react-dotenv && react-scripts build",
  "npm_package_devDependencies_gh_pages": "^6.1.1",
  "SSH_SOCKET_DIR": "~/.ssh",
  "npm_package_eslintConfig_extends_1": "react-app/jest",
  "npm_package_dependencies_react": "^18.2.0",
  "GOPATH": "/Users/jayants/go",
  "npm_package_eslintConfig_extends_0": "react-app",
  "npm_package_dependencies_sass": "^1.86.1",
  "npm_package_dependencies__types_react": "^18.2.67",
  "npm_package_dependencies__testing_library_react": "^14.2.2",
  "npm_config_version_git_sign": "",
  "npm_config_ignore_scripts": "",
  "npm_config_user_agent": "yarn/1.22.22 npm/? node/v23.9.0 darwin arm64",
  "HOMEBREW_CELLAR": "/opt/homebrew/Cellar",
  "INFOPATH": "/opt/homebrew/share/info:",
  "CONDA_CHANGEPS1": "false",
  "npm_config_init_version": "1.0.0",
  "npm_config_ignore_optional": "",
  "npm_package_scripts_eject": "react-scripts eject",
  "npm_package_dependencies__types_react_dom": "^18.2.22",
  "COLORTERM": "truecolor",
  "npm_node_execpath": "/opt/homebrew/Cellar/node/23.9.0/bin/node",
  "npm_config_version_tag_prefix": "v",
  "npm_config_prefix": "/Users/jayants/.npm-global"
};